name: Latest stack overflow activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-medium:
    name: Update this repo's README with latest activity from medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: blog-devrimozcay/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated readme with the latest medium data"
          feed_list: "https://blog-devrimozcay.medium.com/feed"
